### ISSUE TITLE
Crashes on page load

### ISSUE THREAD

**Issue by raidancampbell** [kern/filepizza#10]
After loading the page locally at 127.0.0.1:3000 in Chrome and OSX, I get the following crash

runtime output:

	> filepizza@0.0.0 start /Users/aidan/Desktop/filepizza/filepizza
	> node index.js

	WebDrop listening on 0.0.0.0:3000
	[0mGET / [32m200 [0m33.501 ms - -[0m
	[0mGET /images/up.png [36m304 [0m3.306 ms - -[0m
	[0mGET /images/pizza.png [36m304 [0m0.925 ms - -[0m
	[0mGET /css [32m200 [0m290.000 ms - 6556[0m
	{ [Error: EMFILE, open '/Users/aidan/Desktop/filepizza/filepizza/node_modules/react/package.json']
	  errno: 20,
	  code: 'EMFILE',
	  path: '/Users/aidan/Desktop/filepizza/filepizza/node_modules/react/package.json',
	  stream: 
	   { _readableState: 
	      { highWaterMark: 16,
	        buffer: [],
	        length: 0,
	        pipes: [Object],
	        pipesCount: 1,
	        flowing: true,
	        ended: false,
	        endEmitted: false,
	        reading: true,
	        sync: false,
	        needReadable: true,
	        emittedReadable: false,
	        readableListening: false,
	        objectMode: true,
	        defaultEncoding: 'utf8',
	        ranOut: false,
	        awaitDrain: 0,
	        readingMore: false,
	        decoder: null,
	        encoding: null,
	        resumeScheduled: false },
	     readable: true,
	     domain: null,
	     _events: 
	      { end: [Object],
	        error: [Object],
	        data: [Function: ondata],
	        _mutate: [Object] },
	     _maxListeners: 10,
	     _writableState: 
	      { highWaterMark: 16,
	        objectMode: true,
	        needDrain: false,
	        ending: true,
	        ended: true,
	        finished: true,
	        decodeStrings: true,
	        defaultEncoding: 'utf8',
	        length: 0,
	        writing: false,
	        corked: 0,
	        sync: false,
	        bufferProcessing: false,
	        onwrite: [Function],
	        writecb: null,
	        writelen: 0,
	        buffer: [],
	        pendingcb: 0,
	        prefinished: true,
	        errorEmitted: false },
	     writable: true,
	     allowHalfOpen: true,
	     _options: { objectMode: true },
	     _wrapOptions: { objectMode: true },
	     _streams: [ [Object] ],
	     length: 1,
	     label: 'deps' } }
	[0mGET /js [31m500 [0m3521.111 ms - -[0m
	 

runtime errors:

	/Users/aidan/Desktop/filepizza/filepizza/node_modules/browserify-middleware/node_modules/browserify/index.js:551
	                : opts.basedir || process.cwd()
	                                          ^
	Error: EMFILE, too many open files
	    at globalTr (/Users/aidan/Desktop/filepizza/filepizza/node_modules/browserify-middleware/node_modules/browserify/index.js:551:43)
	    at makeTransform (/Users/aidan/Desktop/filepizza/filepizza/node_modules/browserify-middleware/node_modules/browserify/node_modules/module-deps/index.js:251:21)
	    at /Users/aidan/Desktop/filepizza/filepizza/node_modules/browserify-middleware/node_modules/browserify/node_modules/module-deps/index.js:226:9
	    at Deps.getTransforms (/Users/aidan/Desktop/filepizza/filepizza/node_modules/browserify-middleware/node_modules/browserify/node_modules/module-deps/index.js:231:7)
	    at /Users/aidan/Desktop/filepizza/filepizza/node_modules/browserify-middleware/node_modules/browserify/node_modules/module-deps/index.js:366:24
	    at onresolve (/Users/aidan/Desktop/filepizza/filepizza/node_modules/browserify-middleware/node_modules/browserify/node_modules/module-deps/index.js:178:14)
	    at /Users/aidan/Desktop/filepizza/filepizza/node_modules/browserify-middleware/node_modules/browserify/index.js:480:13
	    at /Users/aidan/Desktop/filepizza/filepizza/node_modules/browserify-middleware/node_modules/browserify/node_modules/browser-resolve/index.js:254:13
	    at onfile (/Users/aidan/Desktop/filepizza/filepizza/node_modules/browserify-middleware/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/asyn
	c.js:51:21)
	    at onex (/Users/aidan/Desktop/filepizza/filepizza/node_modules/browserify-middleware/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.
	js:93:22)

	npm ERR! Darwin 13.4.0
	npm ERR! argv "node" "/usr/local/bin/npm" "start"
	npm ERR! node v0.10.33
	npm ERR! npm  v2.1.11
	npm ERR! code ELIFECYCLE
	npm ERR! filepizza@0.0.0 start: `node index.js`
	npm ERR! Exit status 8
	npm ERR!
	npm ERR! Failed at the filepizza@0.0.0 start script 'node index.js'.
	npm ERR! This is most likely a problem with the filepizza package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node index.js
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls filepizza
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /Users/aidan/Desktop/filepizza/filepizza/npm-debug.log

npm-debug.log:

		cat ./npm-debug.log
		0 info it worked if it ends with ok
		1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
		2 info using npm@2.1.11
		3 info using node@v0.10.33
		4 verbose node symlink /usr/local/bin/node
		5 verbose run-script [ 'prestart', 'start', 'poststart' ]
		6 info prestart filepizza@0.0.0
		7 info start filepizza@0.0.0
		8 verbose unsafe-perm in lifecycle true
		9 info filepizza@0.0.0 Failed to exec start script
		10 verbose stack Error: filepizza@0.0.0 start: `node index.js`
		10 verbose stack Exit status 8
		10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:212:16)
		10 verbose stack     at EventEmitter.emit (events.js:98:17)
		10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
		10 verbose stack     at ChildProcess.emit (events.js:98:17)
		10 verbose stack     at maybeClose (child_process.js:756:16)
		10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
		11 verbose pkgid filepizza@0.0.0
		12 verbose cwd /Users/aidan/Desktop/filepizza/filepizza
		13 error Darwin 13.4.0
		14 error argv "node" "/usr/local/bin/npm" "start"
		15 error node v0.10.33
		16 error npm  v2.1.11
		17 error code ELIFECYCLE
		18 error filepizza@0.0.0 start: `node index.js`
		18 error Exit status 8
		19 error Failed at the filepizza@0.0.0 start script 'node index.js'.
		19 error This is most likely a problem with the filepizza package,
		19 error not with npm itself.
		19 error Tell the author that this fails on your system:
		19 error     node index.js
		19 error You can get their info via:
		19 error     npm owner ls filepizza
		19 error There is likely additional logging output above.
		20 verbose exit [ 1, true ]

**Comment by kern** [comment]
This is caused by Browserify's compilation step opening up tons of NPM modules all at once. To fix, run:

    $ sysctl -w kern.maxfiles=20480
