### ISSUE TITLE
How do I use certbot to secure the site?

### ISSUE THREAD

**Issue by dmarcsift** [kern/filepizza#103]
How would I tie a Let's Encrypt certificate to my docker image? If the need for https fixes the 400 error I get when loading my instance, then I'd like to see if that helps.

**Comment by kern** [comment]
I removed an earlier implementation of this recently — happy to accept a PR that adds this functionality here: https://github.com/kern/filepizza/blob/master/src/server.js#L12-L14

**Comment by dmarcsift** [comment]
So I'm just going to pull requests and opening a new PR there? Not familiar with the process but I see I have limited options on comparing two branches. Not sure how to do this. Would creating a new issue help?

**Comment by kern** [comment]
@dmarcsift if you fork the project, modify it on your own local branch, then push to your fork, you'll be able to create a PR
