### ISSUE TITLE
Update/Improve Zeit-now info on readme

### ISSUE THREAD

**Issue by gnouts** [kern/filepizza#104]
Hi, I just discovered this project (through this : https://github.com/awesome-selfhosted/awesome-selfhosted) and I also just learned about Zeit.

It could fit my need cause it's free lol but instruction seems outdated.

* Parameter `--npm` does not seem to work anymore :
```
$ now --npm --public -e NODE_ENV=production
> Error! Unknown or unexpected option: --npm
```
* Zeit requires that output folder be named `public/` while here it's `dist/`, so it fails ([doc](https://zeit.co/docs/v2/platform/frequently-asked-questions#missing-public-directory)) :
```
$ now --public -e NODE_ENV=production
> Deploying /mnt/c/Users/nouts/Documents/filepizza under nouts
> Using project filepizza
> NOTE: This is the first deployment in the filepizza project. It will be promoted to production.
> NOTE: To deploy to production in the future, run `now --prod`.
> https://filepizza-kcuzco24c.now.sh [2s]
> Error! Build failed
> Error! Check your logs at https://filepizza-kcuzco24c.now.sh/_logs or run `now logs https://filepizza-kcuzco24c.now.sh`
```
* After replacing all `dist` by `public` in the code, it succeeds :
```
$ now --public -e NODE_ENV=production
> Deploying /mnt/c/Users/nouts/Documents/filepizza under nouts
> Using project filepizza
> Synced 1 file [1s]
> https://filepizza-1m1c6clf6.now.sh [4s]
> Ready! Deployed to https://filepizza.nouts.now.sh [35s]
```
* Though, I get a page showing the code :
![zeit](https://user-images.githubusercontent.com/17988185/68778329-548f5600-0633-11ea-8103-bca7df49ba9a.JPG)

I don't know how to debug this... ^^

**Comment by kern** [comment]
I wouldn't suggest deploying on Zeit anymore — they shut down unused instances so it's not a good fit for FilePizza's in-process database. You should probably run the docker image on a long-lived instance.
