### ISSUE TITLE
Branding and translation

### ISSUE THREAD

**Issue by gnouts** [kern/filepizza#105]
Would you consider some changes to let admin translate and rebrand filepizza ?

For example, I want to install filepizza on my server for an assocation but my users are french speaker and I would like to change the spinning pizza by something that match my assocation colors and theme.

Currently, to translate we have to crawl all files in ` src/` and can't blindly replace `FilePizza` because it's also a function name. Maybe having a separate file with only translatable strings ?
Also, images are `arrow.ai` and `pizza.psd` which are not very common format or easily editable. Maybe having PNG format if technically possible ?

**Comment by kern** [comment]
Happy to accept PRs for this!
