### ISSUE TITLE
400: No WebRTC Support

### ISSUE THREAD

**Issue by jrubenc** [kern/filepizza#107]
Hello,

Fresh install with docker 19.03.5 according to docs (the rather simple "docker run..." command).

But... http://77.246.190.114/

_400: No WebRTC Support. Please use Chrome or Firefox._

Same under Chrome or Firefox (latest versions of both browsers).

It's under a 1:1 NAT. Also configured later outbound NAT to use the same public IP address just in case, but didn't help.

Funny thing is that, with Edge, doesn't happen. Let's you pick a file for downloading, but anyway then the download (loading under Edge only also) part doesn't work.

What am I doing wrong? I have the feeling it must be some stupid mistake...

Thanks.

**Comment by jrubenc** [comment]
Doesn't happen under https (proxy_pass under nginx). But it's slow as f*. And doesn't work most of the times.

**Comment by feixia5712** [comment]
Hello, I also encountered a similar problem, how do you solve it, I have a problem with ip: port access
