### ISSUE TITLE
400: No WebRTC Support

### ISSUE THREAD

**Issue by feixia5712** [kern/filepizza#108]
Hello,

Fresh install with docker 19.03.5 according to docs (the rather simple "docker run..." command).

But... ip:8080 

400: No WebRTC Support. Please use Chrome or Firefox.

Same under Chrome or Firefox (latest versions of both browsers).
![Uploading image.png…]()

**Comment by feixia5712** [comment]
![image](https://user-images.githubusercontent.com/12670758/70383747-17a64d00-19ae-11ea-95c2-11d62104ee4d.png)

**Comment by qy527145** [comment]
I also built it with docker, and encountered the same problem during access
我也是用docker搭建的，访问遇到同样的问题

**Comment by SaberDoTcodeR** [comment]
it doesn't occur when using localhost:3000 but when using local ip 192.168.1.x:3000 problem rises

**Comment by kern** [comment]
I believe this is a security property of browsers that blocks WebRTC on insecure pages. Have you tried this using an SSL connection? Not sure if it works with self-signed certs or not.

**Comment by SaberDoTcodeR** [comment]
can you add some tech explanation on how to build project using ssl connection

**Comment by jrubenc** [comment]
OP (@feixia5712) has just copy/pasted my issue at https://github.com/kern/filepizza/issues/107

SSL fixes the error, as I said there. But, anyway, it works when it wants, and is painfully slow af. And it's not a resources problem...

**Comment by jrubenc** [comment]
@SaberDoTcodeR 
> can you add some tech explanation on how to build the project using SSL connection

https://github.com/kern/filepizza/issues/100

Supposedly fixed in October. Doesn't work. What runs under https://file.pizza/ is not the same here on Github and/or lacks documentation. For example, https://file.pizza/ is hosted on CloudFlare and SSL is ended/proxied there.

**Comment by kern** [comment]
I've released a new update that supports initializing FilePizza with an HTTPS TLS cert/key, please check the README. Could you let me know if this helps?

**Comment by jrubenc** [comment]
Fair enough. For the sake of clarity, I won't obscure the hostname for debugging.

Docker inspect for the container: https://pastebin.com/pyUdhn0N

    # docker version
    Client: Docker Engine - Community
     Version:           19.03.5

    # docker run -d -p 8080:8080 -e PORT=8080 -e HTTPS_KEY=/config/server.key -e HTTPS_CERT=/config/server.crt -v mylocalpath:/config  kern/filepizza:master
    fe17dd8453b7133dc5664978f51fa7ed7f681a36ff6c9784a29ee5560794ddf1

And when requested:

    # curl -v https://files.apmgestio.cat:8080  
    * Rebuilt URL to: https://files.apmgestio.cat:8080/
    *   Trying 77.246.190.51...
    * TCP_NODELAY set
    * Connected to files.apmgestio.cat (77.246.190.51) port 8080 (#0)
    * ALPN, offering h2
    * ALPN, offering http/1.1
    * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
    * successfully set certificate verify locations:
    *   CAfile: /etc/ssl/certs/ca-certificates.crt
      CApath: /etc/ssl/certs
    * TLSv1.2 (OUT), TLS header, Certificate Status (22):
    * TLSv1.2 (OUT), TLS handshake, Client hello (1):
    * TLSv1.2 (IN), TLS handshake, Server hello (2):
    * TLSv1.2 (IN), TLS handshake, Certificate (11):
    * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
    * TLSv1.2 (IN), TLS handshake, Server finished (14):
    * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
    * TLSv1.2 (OUT), TLS change cipher, Client hello (1):
    * TLSv1.2 (OUT), TLS handshake, Finished (20):
    * TLSv1.2 (IN), TLS change cipher, Client hello (1):
    * TLSv1.2 (IN), TLS handshake, Finished (20):
    * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
    * ALPN, server accepted to use http/1.1
    * Server certificate:
    *  subject: CN=files.apmgestio.cat
    *  start date: Dec 26 14:01:34 2019 GMT
    *  expire date: Mar 25 14:01:34 2020 GMT
    *  subjectAltName: host "files.apmgestio.cat" matched cert's "files.apmgestio.cat"
    *  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
    *  SSL certificate verify ok.
    > GET / HTTP/1.1
    > Host: files.apmgestio.cat:8080
    > User-Agent: curl/7.52.1
    > Accept: */*
    > 

hangs there forever.

**Comment by kern** [comment]
@jrubenc give the latest build a whirl, 3e3f46ba7b716da8324ae34220d325b64e268365 should have fixed the hanging issue. Thanks for the report.

**Comment by jrubenc** [comment]
@kern seems to work now :) Directly on 443:

https://files.apmgestio.cat

Added http->https with nginx (would be nice if you created an insecure listener and 301 the requests to the https one).

**Comment by feixia5712** [comment]
ok
