### ISSUE TITLE
Cannot find module './lib/babel/api/register/node'

### ISSUE THREAD

**Issue by hferee** [kern/filepizza#11]
`npm: 2.9.1`
`node: 0.10.38`

npm install goes without errors, only a few warnings of the form:
`requires parseuri@'0.0.4' but will load`

However, `npm start` halts on:
>Error: Cannot find module './lib/babel/api/register/node'
>    at Function.Module._resolveFilename (module.js:338:15)
>    at Function.Module._load (module.js:280:25)
>   at Module.require (module.js:364:17)
>    at require (module.js:380:17)
>    at Object.<anonymous> (/home/pi/filepizza/node_modules/babel/register.js:1:80)
>    at Module._compile (module.js:456:26)
>    at Object.Module._extensions..js (module.js:474:10)
>    at Module.load (module.js:356:32)
>    at Function.Module._load (module.js:312:12)
>    at Module.require (module.js:364:17)`

**Comment by kern** [comment]
Seems to be an issue with older versions of Node. I've bumped the version requirement to `0.12.x` in 0cff.
