### ISSUE TITLE
Trackers not reachable on Firefox

### ISSUE THREAD

**Issue by redpandamonium** [kern/filepizza#110]
When providing or downloading files Firefox can't connect to 
`tracker.btorrent.xyz`
`tracker.fastcast.nz`
`tracker.openwebtorrent.com`
Fails with error: `Firefox can't establish a connection to the server at wss://x`

**Comment by schmittlauch** [comment]
This happens in other browsers as well.

Example from the Chromium-based browser Falkon:

```
WebSocket connection to 'wss://tracker.fastcast.nz/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
r @ webtorrent.min.js:7
webtorrent.min.js:7 WebSocket connection to 'wss://tracker.openwebtorrent.com/' failed: Error during WebSocket handshake: Unexpected response code: 520
r @ webtorrent.min.js:7
webtorrent.min.js:7 WebSocket connection to 'wss://tracker.fastcast.nz/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
```

**Comment by kern** [comment]
I have started hosting a bittorrent-tracker instance for the hosted version of filepizza.
