### ISSUE TITLE
file.pizza doesn't work anymore after updates

### ISSUE THREAD

**Issue by jligeza** [kern/filepizza#112]
I use file.pizza for a long time, and after an update which changed (probably among other things) how download url is built, I cannot send anything to anybody. When the download button is pressed, the files are never transfered.

I use newest chrome on linux, and the other people use various operating systems (linux, mac, windows), and many different web browsers. Tried sending both big and small files, but it never worked.

**Comment by kern** [comment]
Investigating this, able to reproduce. thanks for the report @jligeza

**Comment by kirushik** [comment]
Probably related to https://github.com/webtorrent/webtorrent/issues/1812#issuecomment-581321591; I also think #110 is the same issue as this one.

**Comment by kern** [comment]
Thanks @kirushik — I believe you're right. Closing in favor of #110
