### ISSUE TITLE
"Like FilePizza" banner blocks QR code

### ISSUE THREAD

**Issue by stephen304** [kern/filepizza#115]
I'm not exactly sure why, but on my PC that's hooked up to a TV, the lower banner blocks part of the QR code. I'm not sure if it's related to windows scaling for the TV or what, but it's a bit annoying since the banner can't be dismissed so I have to type out the url instead of being able to scan the QR code. It may just be easiest to add that much padding to the bottom of a page-wide element to allow you to scroll that much further.

<img width="960" alt="Capture2" src="https://user-images.githubusercontent.com/981915/74597986-f65d7f00-5036-11ea-98d0-c5e9b6f12f7f.PNG">

**Comment by kern** [comment]
I think I've fixed it in a recent update, mind checking @stephen304?
