### ISSUE TITLE
Running FilePizza fails 

### ISSUE THREAD

**Issue by Feliix42** [kern/filepizza#12]
Hey, after I tried to install FilePizza on a CentOS 6 - Server featuring shared hosting,
`$ npm start` 
gave me the following errors:

![error](https://cloud.githubusercontent.com/assets/9332912/7678649/1f64548e-fd56-11e4-847f-c401be1fee02.png)

During the installation, there was one error:
`npm WARN optional dep failed, continuing fsevents@0.3.6`

The error log can be found on [lpaste.net](http://lpaste.net/132847)

**Comment by kern** [comment]
Port 3000 is currently in use. You can specify the port using the `PORT` environment variable:

    $ env PORT=80 npm start

Added a note about this to the README in 779b4b7.
