### ISSUE TITLE
file.pizza doesn't work

### ISSUE THREAD

**Issue by optimistic5** [kern/filepizza#123]
file.pizza doesn't work.
I tried latest Firefox and Chrome; Linux, Windows; desktop, smartphone;  different counties, no luck.

I selected a file to share
![image](https://user-images.githubusercontent.com/25054050/83676818-eff21380-a5e3-11ea-9b61-563b6e31fc26.png)

I opened URL in another computer (another IP and location), pressed download button and see **Peers: 0 · Up: 0 Bytes · Down: 0 Bytes**
![image](https://user-images.githubusercontent.com/25054050/83677104-55de9b00-a5e4-11ea-8113-6065ad55df90.png)

Does it works for you?
Please, let me know if you need any logs from me.

**Comment by andrekutianski** [comment]
![image](https://user-images.githubusercontent.com/5316107/83695717-ffb42c80-a5d0-11ea-9a99-3a2a7466161d.png)

**Comment by alexpear** [comment]
I also have this problem. It doesnt even work with 2 tabs of the same browser.

**Comment by lameguest21** [comment]
yes doesnt work

**Comment by Tinoooo** [comment]
For anyone looking for an alternative: I think instant.io is a pretty good substitute.

**Comment by milanovitch44** [comment]
It has something to do with the server rendering the page instead of the client.

When I run `npm start`, I can download it in another tab without any problems.

**Comment by KonradLinkowski** [comment]
@kern could you look into that?

**Comment by sc84647** [comment]
I get the same issue, with the same Invariant Violation error in the console

**Comment by joshuaganger** [comment]
Still broken in Chrome & Firefox.  I'll second instant.io - appears to have the same form and function (just missing the cute pizza topping path).  Major advantage is that it works!

**Comment by Mopfus** [comment]
Same for me. It does not work at all. I trief instant.io but their GUI is very ugly and has less good functions. I like the idea if the link as ingredients. And also the qr code is quite handy. 
Very sad that this very nice software is not working any more. 😭

**Comment by jacktose** [comment]
> I trief instant.io but their GUI is very ugly and has less good functions.

@Mopfus You might prefer https://wormhole.app (which is linked from https://instant.io).

**Comment by escape0707** [comment]
@jacktose That site seems to be not open sourced and try to let me upload smaller files before I'm able to share them p2p with others.

Actually, I've figured out that transferring files though UDP to my friend with ISP's firewall's censorship is not reliable as UDP usually got throttled. Now I just use `miniserve` + `Freenom` + `CloudFlare DNS` + `Let's Encrypt` combo to host a mini website and share files to them through HTTPS.

**Comment by Mopfus** [comment]
> > I trief instant.io but their GUI is very ugly and has less good functions.
> 
> @Mopfus You might prefer https://wormhole.app (which is linked from https://instant.io).

Nope. I don’t want to upload my files to some random server I don’t know. The idea of a pizza is p2p. And that’s a great idea! This one wormhole thing has nothing to do with P2P.

**Comment by Technetium1** [comment]
@Mopfus I've been using
- https://github.com/schollz/croc (my favorite)
- https://github.com/szimek/sharedrop
- https://justbeamit.com/ (closed source I think)

**Comment by Mopfus** [comment]
@Technetium1 
AWESOME! Thank you very much. At the moment I like sharedrop the most, but I will keep on testing a little bit more. The thing for such tools is, that it has to be easy-to-use for nomal-not-tech-users. Because then they are needed the most. So that not dad wants to send all the 100 holiday pictures via WhatsApp or so...

**Comment by Technetium1** [comment]
@Mopfus my advice is to teach how to compress a folder of stuff, and justbeamit over, since it's the most user friendly I've come across so far. If you were super motivated, you could make a simple wrapper for croc with pyinstaller or something to initialize outgoing transfers.

**Comment by T0P0ICHH** [comment]
https://v0dev.cfd

**Comment by aluvalasathish** [comment]
Alternative for file pizza is airlynk.in
AirLynk offers a more robust and user-friendly solution for peer-to-peer file transfers:

>Reliable Transfers: AirLink ensures stable connections, even in challenging network conditions, minimizing the chances of transfer failures.
>Cross-Browser Compatibility: Unlike FilePizza, AirLynk provides consistent performance across all major browsers without relying on WebRTC, reducing compatibility issues.
>Active Development: AirLynk is actively maintained, ensuring regular updates and improvements to keep up with evolving web standards and user needs.
>User-Friendly Interface: AirLynk's intuitive design makes it easy for users to initiate and complete file transfers without technical hassles.
