### ISSUE TITLE
file.pizza doesn't work YET

### ISSUE THREAD

**Issue by rbernardes** [kern/filepizza#125]
I cloned the project and then run docker-compose up, with a reverse proxy on nginx, without success.
I try to use https://file.pizza/, without success too.
The logs give me no clue.
Any tip?
https://filepizza.at.wiki.br

**Comment by vRobM** [comment]
it works, but you have to be patient and let the DHT network find your friend.

**Comment by lameguest21** [comment]
It doesn't work for me as well. niether downloading nor uploading 
![image](https://user-images.githubusercontent.com/35087196/93718689-661e8400-fb9b-11ea-8b14-4b190eccfb7a.png)

**Comment by James-Lester** [comment]
Is this an abandoned project?

**Comment by stlxiii** [comment]
Looks like it abandonned :(
Doesn't work for me either, using Firefox, Chrome on PC, Safari on Mac and iOS.  Just... hangs there and does nothing.

**Comment by vRobM** [comment]
Works for me - https://fp. toldyouso.com/

++ Rob

*About me <https://about.me/vRobM>*

**Comment by rbernardes** [comment]
Ok, got it!
Docker-compose -> wont work
docker run -> work
