### ISSUE TITLE
kinda broken

### ISSUE THREAD

**Issue by beckend** [kern/filepizza#14]
file.pizza instance:
WebSocket connection to 'ws://file.pizza/peer/peerjs?key=peerjs&id=5c282d4a-ee71-4849-a2b1-180f76218220&token=j4khg3a8yg44pldi' failed: Error during WebSocket handshake: Unexpected response code: 404
js:11 WebSocket connection to 'ws://file.pizza/socket.io/?EIO=3&transport=websocket&sid=Pl4_msu7sxmnnMCzABK0' failed: Error during WebSocket handshake: Unexpected response code: 400
js:1 Uncaught TypeError: Cannot read property 'on' of undefined
js:11 WebSocket connection to 'ws://file.pizza/socket.io/?EIO=3&transport=websocket&sid=NTr7iT3r4azxVwyfABK2' failed: Error during WebSocket handshake: Unexpected response code: 400

A local instance listens, but when you visit the site no Js nor css is loaded, just plain HTML.

**Comment by kern** [comment]
Thanks for reporting this @beckend, going to dive into this tonight.

**Comment by kern** [comment]
Was unable to replicate this locally, and http://file.pizza seems to be working. Any details about your setup that could be the issue? Perhaps older versions of deps?

**Comment by beckend** [comment]
So I have retested it again, it wasn't finding babelify module and failed hard, I did "export NODE_PATH=/correct/path" to find it. As for the Js and Css, I've got a EACCES error (filepizza was installed with npm -g) and corrected permissions for my User.
