### ISSUE TITLE
File transfer does not start (same network)

### ISSUE THREAD

**Issue by kepler2** [kern/filepizza#146]
Hello.

Thanks for the hard work.

The issue is that the file transfer does not start.

**Steps:**
1 - Go to https://file.pizza/
2 - Select a file
3 - Scan the QR code from a smartphone from the same WIFI
4 - Open the link in Chrome

**Result:**
Nothing happens.

**Expected:**
The file transfer should start.

**Comment by castilma** [comment]
Maybe duplicate of #125? The webmaster of file.pizza maybe used `docker-compose up` instead of `docker run`?

**Comment by Jack-Edwards** [comment]
Allow me to plug an alternative service that does work: https://github.com/Crypter-File-Transfer/Crypter

I probably wouldn't have built it if https://file.pizza were still working.

**Comment by camAtGitHub** [comment]
I have never got this to work.
Try wormhole.io or sharedrop.io for alternatives
