### ISSUE TITLE
It does not work for me

### ISSUE THREAD

**Issue by josecelano** [kern/filepizza#159]
[Version 1.65.114 Chromium: 124.0.6367.60 (Official Build) (64-bit)](https://brave.com/latest/)

I can click on download but I can't download the file.

I'm getting this error:

![image](https://github.com/kern/filepizza/assets/58816/f8d24b43-4a07-4f1d-8ec8-32a1634ae126)

**Comment by opheliagame** [comment]
I am having the same issue. I think this has been happening for a while now.

**Comment by theomgdev** [comment]
The connection broker server of filepizza is broken I guess. It would be best if you ran your connection broker. Yes, WebRTC is serverless but still a client needs to know other client's info to connect. So a broker holds and serves the info and provides a tunnel to save users from hustle of opening ports etc. Take a look: https://github.com/peers/peerjs-server

**Comment by iuvi7** [comment]
For me doesn't work too :(

**Comment by NanoAi** [comment]
Getting the same errors on Firefox and LibreWolf as well.
