### ISSUE TITLE
site down?

### ISSUE THREAD

**Issue by winkler1** [kern/filepizza#16]
Currently --

This webpage is not available

ERR_CONNECTION_REFUSED

**Comment by anubiann00b** [comment]
Is this a duplicate of #17?

**Comment by winkler1** [comment]
@anubiann00b  No. 17 is running locally, 16 is the file.pizza site.

**Comment by kern** [comment]
Been getting some sporadic crashes on the FilePizza instance. Just pushed a few commits that add better logging through Winston. New Relic is also now monitoring the instance with pings. If I get one of these crashes again, I'll dive in and figure out what's going on. Thanks for the report!
