### ISSUE TITLE
filepizze terminating without error

### ISSUE THREAD

**Issue by arminus** [kern/filepizza#19]
Hey,

just installed filepizza as advertised on a Ubuntu 12.04 LTS (with node 0.12.7), starting it looks like this:

env PORT=3457 filepizza
FilePizza listening on :::3457

and then it returns to the prompt without any error messages. There's also no background process or something (already) listening on 3457.

Any idea?

**Comment by tvvocold** [comment]
@kern 
Me too, i had stop the firewalld in Fedora 22 but it didn't work.

**Comment by kern** [comment]
Should be fixed in `0.2.2`. I removed the runtime dependency on Babel, which seemed to be the issue.
