### ISSUE TITLE
Any chance of a FOSS license?

### ISSUE THREAD

**Issue by Bugsbane** [kern/filepizza#27]
Not demanding. Just asking. :) Either copyleft or permissive., although AGPL could be an interesting consideration for a network service like this.

**Comment by kern** [comment]
FilePizza is already BSD 3-clause. :)

**Comment by Bugsbane** [comment]
Really? I just looked and the LICENSE file in the root folder says:

"Copyright (c) 2015, Alex Kern
All rights reserved."

And doesn't have any mention of BSD in it anywhere...

**Comment by kern** [comment]
It's at the bottom of the readme. The LICENSE file contains the actual text of the license: http://opensource.org/licenses/BSD-3-Clause

**Comment by Bugsbane** [comment]
Ah ok. Thanks.
