### ISSUE TITLE
.htaccess RewriteRule fails

### ISSUE THREAD

**Issue by tristan-k** [kern/filepizza#28]
I'm using a [shared-hoster](https://uberspace.de/) which only allows ports between 61000 and 65535. For this reasons I want to redirect the port to the subdomain [files.tristank.de](http://fp.tristank.de). Normally this works great but for filepizza it just keeps downloading the index page as a file named `download` as soon as I browse to [files.tristank.de](http://files.tristank.de). Accessing filepizza directly with [tristank.de:65150](http://tristank.de:65150) does work. Any suggestions?

`.htaccess`

```
RewriteEngine On
RewriteRule ^(.*) http://localhost:65150/$1 [P]
```

---

```
$ curl -sL 'http://fp.tristank.de'
```

`<!DOCTYPE html>
<html lang="en" data-reactid=".l1zogtimm8" data-react-checksum="-1529270282"><head data-reactid=".l1zogtimm8.0"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta property="og:url" content="http://file.pizza"><meta property="og:title" content="FilePizza - Your files, delivered."><meta property="og:description" content="Peer-to-peer file transfers in your web browser."><meta property="og:image" content="http://file.pizza/images/fb.png"><title>FilePizza - Your files, delivered.</title><link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Quicksand:300,400,700|Lobster+Two"><link rel="stylesheet" href="/css"><script id="bootstrap" type="application/json">{"ErrorStore":{"status":404,"message":"Not Found","stack":null},"SupportStore":{"isSupported":true,"isChrome":false},"DownloadStore":{"fileName":"","fileSize":0,"fileType":"","infoHash":null,"peers":0,"progress":0,"speedDown":0,"speedUp":0,"status":"uninitialized","token":null},"UploadStore":{"fileName":"","fileSize":0,"fileType":"","infoHash":null,"peers":0,"speedUp":0,"status":"ready","token":null}}</script><script src="/js"></script></head><body data-reactid=".l1zogtimm8.1"><div class="container" data-reactid=".l1zogtimm8.1.0"><div class="drop-zone" data-reactid=".l1zogtimm8.1.0.0"><div class="drop-zone-overlay" hidden data-reactid=".l1zogtimm8.1.0.0.0"></div><div class="page" data-reactid=".l1zogtimm8.1.0.0.1"><div class="spinner" data-reactid=".l1zogtimm8.1.0.0.1.0"><div class="spinner-content" data-reactid=".l1zogtimm8.1.0.0.1.0.0"><img alt="up" src="/images/up.png" class="spinner-image" data-reactid=".l1zogtimm8.1.0.0.1.0.0.0"></div><img src="/images/pizza.png" class="spinner-background" data-reactid=".l1zogtimm8.1.0.0.1.0.1"></div><h1 data-reactid=".l1zogtimm8.1.0.0.1.1">FilePizza</h1><p data-reactid=".l1zogtimm8.1.0.0.1.2">Free peer-to-peer file transfers in your browser.</p><p data-reactid=".l1zogtimm8.1.0.0.1.3">We never store anything. Files only served fresh.</p><p data-reactid=".l1zogtimm8.1.0.0.1.4"><label class="select-file-label" data-reactid=".l1zogtimm8.1.0.0.1.4.0"><input type="file" required data-reactid=".l1zogtimm8.1.0.0.1.4.0.0"><span data-reactid=".l1zogtimm8.1.0.0.1.4.0.1">select a file</span></label></p></div></div></div><footer class="footer" data-reactid=".l1zogtimm8.1.1"><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank" data-reactid=".l1zogtimm8.1.1.0"><input type="hidden" name="cmd" value="_s-xclick" data-reactid=".l1zogtimm8.1.1.0.0"><input type="hidden" name="encrypted" value="-----BEGIN PKCS7-----MIIHLwYJKoZIhvcNAQcEoIIHIDCCBxwCAQExggEwMIIBLAIBADCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwDQYJKoZIhvcNAQEBBQAEgYCNMeG6YZhT922YX4RX+GjBbjswhfVoq4+fSNlIliwLOy53+8F+Yo4cMww5pGns0JnRACe8juYZxFVJ9MwBTUfTY+tqLrjer4WraF+Ron5ltsHxZIycWiSMwLByQkB+PXOGRQS8FXPYOUtsuzSaAtQd2aIU1NqgUDFrx2wFkbfl/DELMAkGBSsOAwIaBQAwgawGCSqGSIb3DQEHATAUBggqhkiG9w0DBwQI9iG7UFroYuOAgYjTfNDjke+5a4E/GKdXiGtu2UTTAwRuf+lvJi/REu8wrJqQYWTwzdxltDsDzC4NRkBzysqAq/2NTjMJw91X5hSsEGSP4yn2AGY2ZstPBwlha0NRtCnZj6ZKO5b7Yqi5m0zQQSLVsEjb8ZQPBQCykSq5vuJXLbjXx8PSCpBCQ5jfVdbuEADyDXr+oIIDhzCCA4MwggLsoAMCAQICAQAwDQYJKoZIhvcNAQEFBQAwgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tMB4XDTA0MDIxMzEwMTMxNVoXDTM1MDIxMzEwMTMxNVowgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDBR07d/ETMS1ycjtkpkvjXZe9k+6CieLuLsPumsJ7QC1odNz3sJiCbs2wC0nLE0uLGaEtXynIgRqIddYCHx88pb5HTXv4SZeuv0Rqq4+axW9PLAAATU8w04qqjaSXgbGLP3NmohqM6bV9kZZwZLR/klDaQGo1u9uDb9lr4Yn+rBQIDAQABo4HuMIHrMB0GA1UdDgQWBBSWn3y7xm8XvVk/UtcKG+wQ1mSUazCBuwYDVR0jBIGzMIGwgBSWn3y7xm8XvVk/UtcKG+wQ1mSUa6GBlKSBkTCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb22CAQAwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQUFAAOBgQCBXzpWmoBa5e9fo6ujionW1hUhPkOBakTr3YCDjbYfvJEiv/2P+IobhOGJr85+XHhN0v4gUkEDI8r2/rNk1m0GA8HKddvTjyGw/XqXa+LSTlDYkqI8OwR8GEYj4efEtcRpRYBxV8KxAW93YDWzFGvruKnnLbDAF6VR5w/cCMn5hzGCAZowggGWAgEBMIGUMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbQIBADAJBgUrDgMCGgUAoF0wGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMTUwNzAxMDM1NDUxWjAjBgkqhkiG9w0BCQQxFgQUG4ncyq0gUI2wN0Td/HxNnvNQnYowDQYJKoZIhvcNAQEBBQAEgYBYA6JGTfR4lLMQe/4tItu1Y6Dp76QyZc2yx2I5B/Z7QEVGqdiFi0lPdXhbKjS0nSzdx30vHKzvowrI12uTkdQVT0lA0xLgVMQ2761anl8mQA94wnGvR0onQAeQOT7giMU8rrUkINIWpnYVTfEAjCH90uXM4+SnIx7+OPLEu698Og==-----END PKCS7-----" data-reactid=".l1zogtimm8.1.1.0.1"><button type="submit" class="donate-button" data-reactid=".l1zogtimm8.1.1.0.2">donate via PayPal</button><p data-reactid=".l1zogtimm8.1.1.0.3"><span data-reactid=".l1zogtimm8.1.1.0.3.0">BTC: </span><strong data-reactid=".l1zogtimm8.1.1.0.3.1">1P7yFQAC3EmpvsB7K9s6bKPvXEP1LPoQnY</strong></p></form><p class="byline" data-reactid=".l1zogtimm8.1.1.1"><span data-reactid=".l1zogtimm8.1.1.1.0">Cooked up by </span><a href="http://kern.io" target="_blank" data-reactid=".l1zogtimm8.1.1.1.1">Alex Kern</a><span data-reactid=".l1zogtimm8.1.1.1.2"> &amp; </span><a href="http://neeraj.io" target="_blank" data-reactid=".l1zogtimm8.1.1.1.3">Neeraj Baid</a><span data-reactid=".l1zogtimm8.1.1.1.4"> while eating </span><strong data-reactid=".l1zogtimm8.1.1.1.5">Sliver</strong><span data-reactid=".l1zogtimm8.1.1.1.6"> @ UC Berkeley · </span><a href="https://github.com/kern/filepizza#faq" target="_blank" data-reactid=".l1zogtimm8.1.1.1.7">FAQ</a><span data-reactid=".l1zogtimm8.1.1.1.8"> · </span><a href="https://github.com/kern/filepizza" target="_blank" data-reactid=".l1zogtimm8.1.1.1.9">Fork us</a></p></footer><script data-reactid=".l1zogtimm8.1.2">FilePizza()</script><script data-reactid=".l1zogtimm8.1.3"></script></body></html>`

**Comment by tristan-k** [comment]
Still having trouble with this.

**Comment by tristan-k** [comment]
Bump

**Comment by kern** [comment]
@tristan-k You might need to set the content-type to text/html for the rewrite rule.

**Comment by tristan-k** [comment]
@kern Thanks! How do I do that? I followed an answer on [stackoverflow](https://stackoverflow.com/questions/16397195/how-to-mod-rewrite-based-on-http-header-content-type), but it still downloads a file called `download`. Any advice?

`.htaccess`

```
RewriteEngine On
RewriteCond %{HTTP:Accept} text/html [NC]
RewriteRule ^(.*) http://localhost:65150/$1 [P]
```

**Comment by jan0e** [comment]
@tristan-k Since I am facing the same problem: did you ever resolved that issue?

**Comment by tristan-k** [comment]
@jan0e No I did not. I gave up.

**Comment by kern** [comment]
I'm planning a full rewrite of this project fixing the WebTorrent connectivity issues, simplifying serving (which should hopefully fix this issue), using redux, and having an optional encryption password to prevent server operators from tapping into download streams. Will keep this thread updated with progress, especially on the serving component!
