### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Ashtor** [kern/filepizza#29]
Hi, 
Since I dont find any new thread for suggestions,I post it under "Issues". Here are my suggestions anyway:
1. Get ddos protection
2. Make it impossible to reveal the sites IP (no matter where you try to resolve the site to get the IP)
3. Make the site https://

**Comment by KristobalJunta** [comment]
@Ashtor it seems to serve https:// by default already

**Comment by Ashtor** [comment]
the site yl.io doesn't work. please put it back up

**Comment by kern** [comment]
@Ashtor 

1. using kubernetes, traefik, and Route 53 now which is working well for the current traffic the site gets. if this becomes an issue I'll throw cloudflare in the mix.
2. through a Tor hidden service?
3. done. :)

I don't run yl.io.
