### ISSUE TITLE
fails on mobile 

### ISSUE THREAD

**Issue by Dmole** [kern/filepizza#33]
Chrome and firefox for android can use other webrtc tools but both crash on webtorrent with a 2GB file... maybe it's trying to store the whole file in ram instead of only the chunk hashes.

**Comment by kern** [comment]
Pretty sure it's impossible given current web standards to incrementally write a file to disk. :(

**Comment by Dmole** [comment]
So maybe the UI should state that limitation instead of crashing the browser with no explanation. Like only proceed if the user said yes to `confirm("Is your file/torrent size (" + size + ") less than the free RAM on this device?");`
