### ISSUE TITLE
Does not properly unbind events in React components

### ISSUE THREAD

**Issue by fpayer** [kern/filepizza#34]
I was looking at some of the React components and noticed that the "componentDidUnmount" function was being used to unbind event listeners. However, this it not a valid function in the React lifecycle and is never called. The correct function is "componentWillUnmount".

Here is one such example, but I feel as if there are more.
https://github.com/kern/filepizza/blob/master/lib/components/ChromeNotice.js

**Comment by kern** [comment]
Happy to merge a PR on this, thanks @fpayer!
