### ISSUE TITLE
Minor SSL issue at file.pizza

### ISSUE THREAD

**Issue by icheyne** [kern/filepizza#35]
The certificate chain is incomplete. I think this is causing issues in some browsers.

https://www.ssllabs.com/ssltest/analyze.html?d=file.pizza

I believe an intermediate certificate needs to be installed, but don't ask me for specifics. :-)

**Comment by iocon** [comment]
Missing intermediate cert? It gives an error on chrome for Android...

**Comment by nwgat** [comment]
FYI https://letsencrypt.org/

**Comment by kern** [comment]
Fixed, thanks! :)

**Comment by icheyne** [comment]
Grade A! Well done. :-)
