### ISSUE TITLE
Big file ?

### ISSUE THREAD

**Issue by flamme-demon** [kern/filepizza#36]
Hello,

I wanted to send a 1.8go file named "RM1104_059X4S9_1078.0038.10586.13080.13842.033255.zip" and impossible to have a link I have a bias .

**Comment by kern** [comment]
Did you try using Firefox? Files > 500mb don't work in Chrome.

**Comment by flamme-demon** [comment]
I use Chrome , Opera or edge ! A correction will soon be put in place to correct this problem ?

**Comment by kern** [comment]
It's a long-standing issue in WebKit-based browsers (Chrome, Opera). Not sure about Edge. Please use Firefox for now.
