### ISSUE TITLE
Needs more readme :)

### ISSUE THREAD

**Issue by Maximilianos** [kern/filepizza#4]
This looks like a cool project, could you write up how it works and whatever else might be relevant in the Readme? Would be good to get that sort of overview when landing on the repo. or link up to a blog post or something :)

**Comment by CREEATION** [comment]
:+1:

**Comment by neerajbaid** [comment]
Added some basic overview--anything else you'd like to see?

**Comment by Maximilianos** [comment]
Nice, thanks.

**Comment by kern** [comment]
I think it'd also be good to have some information about how the app is structured from a high-level. Will address this after finals. ;)
