### ISSUE TITLE
Compatibility for self-hosted signalling/STUN/TURN server

### ISSUE THREAD

**Issue by rugk** [kern/filepizza#40]
It would be nice to be able to self-host the signalling, STUN & TURN server (e.g. using https://github.com/andyet/signalmaster) and be able to use it with FilePizza.

Related to https://github.com/kern/filepizza/issues/39

**Comment by kern** [comment]
Happy to merge a PR on this.

**Comment by kern** [comment]
You can now do this via env var `ICE_SERVERS`. :)

**Comment by rugk** [comment]
Nice, and good to see this is being developed again… :smile:
