### ISSUE TITLE
Does not send Content-Type

### ISSUE THREAD

**Issue by rugk** [kern/filepizza#46]
If you already use such crappy URLs such as `/js` or `/css` you should at least send the correct Content-Type header.
Even for the index page no Content-Type header is sent.

**Comment by kern** [comment]
Happy to merge a PR on this.

No need to be angry! They're just URLs. :)

**Comment by NeoXiD** [comment]
@kern It is not just URLs in this case, not sending a correct Content-Type means that this application will break whenever proxied behind a webserver sending "X-Content-Type-Options: nosniff" to their visitors, which more and more people are starting to do. It's a security feature, telling the browser to stop overriding the MIME type received from the server or guessing it if no header was sent, like in this case.

This will obviously lead to the fact that the index page gets displayed as text/plain. I'll try to work out a PR for that.

**Comment by rugk** [comment]
> unless your brain has its own HTML render engine. I'll try to work out a PR for that.

Oh awesome, how do I load this into my brain when it is finished? :stuck_out_tongue_winking_eye:
(seriously, btw, nice of you to do so)

**Comment by NeoXiD** [comment]
@rugk: Haha! Was actually easy to fix, but there's so much other stuff that would need to be done. A few more PRs might follow when I get more time to do so. Now just waiting for @kern to merge, my updated branch is working on my server with **X-Content-Type-Options** set to **nosniff**.
