### ISSUE TITLE
React: Invariant Violation

### ISSUE THREAD

**Issue by rugk** [kern/filepizza#49]
I always get this JS error:

```
Error: Invariant Violation: You're trying to render a component to the document using server rendering but the checksum was invalid. This usually means you rendered a different component type or props on the client from the one on the server, or your render() methods are impure. React cannot handle this case due to cross-browser quirks by rendering at the document root. You should look for environment dependent code in your components and ensure the props are the same client and server side:
 (client) <html lang="en" data-react
 (server) <html data-reactid=".1tf8p
```

And yes I have modified the JS/HTML code a bit, but I recompiled everything using `make build`, so I thought it should be working.
How can I remove this checksum?

**Comment by rugk** [comment]
So it happens when I modify `src/components/App.js` and then run `make build`.
(I use Node JS in production mode here.)

It does not matter what I change, React will always complain about it. Even if it is just a path to an image or so...

How can I circumvent this?

**Comment by rugk** [comment]
Okay, I also get this error when using the `npm install` version without any modifications.

**Comment by rugk** [comment]
@kern How can I get that working?

**Comment by kern** [comment]
This happens because I'm doing server-side rendering in dev, which means updating the views requires a restart (at the moment). Can't replicate this issue when unmodified, so closing. I might throw nodemon into the mix to fix the development workflow, willing to accept PRs for this.

**Comment by rugk** [comment]
Actually I restarted the FilePizza some times after modifying the files and even when they are unmodified I could reproduce this issue.

If you have any tips how to debug this, I would be very grateful.

**Comment by kern** [comment]
What commands are you using? A standard `make` should work.

**Comment by rugk** [comment]
`make build` and then executing `dist/index.js`.

I just adjusted the file paths ( `app.js` and `app.css` and so on) before (see https://github.com/kern/filepizza/issues/59) and afterwards ran the build process as explained above.
