### ISSUE TITLE
filepizza-socket is not in the npm registry 

### ISSUE THREAD

**Issue by qjouda** [kern/filepizza#5]
npm install isn't working ... 

npm ERR! 404 'filepizza-socket' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.13.0-52-generic
npm ERR! command "/home/qusai/.nvm/v0.10.22/bin/node" "/home/qusai/.nvm/v0.10.22/bin/npm" "install"
npm ERR! cwd /home/qusai/github.com/filepizza
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! code E404

**Comment by cbrachem** [comment]
Update npm. I just had the same problem with an old node/npm installation that I had lying around. A fresh install of node resolved the problem (npm didn't want to update beyong version 1.3.14). The current version of npm is 2.7.4.

**Comment by hferee** [comment]
You should maybe precise in the readme the version of npm that filepizza depends on.

**Comment by hferee** [comment]
Note that npm 1.4.21 is not sufficient either:
"No compatible version found: babel@'^4.7.16'"

**Comment by kern** [comment]
Added a note about npm and node version requirements to the README in 04cc8d9b7b8df8caeabb7b36e77bc1f8def642e1. Thanks for letting us know!

**Comment by qjouda** [comment]
Thanks
