### ISSUE TITLE
Slow uploads

### ISSUE THREAD

**Issue by Ashtor** [kern/filepizza#53]
Hi.
It seems that the file,pizza site takes time to upload files. Check out the site https://filetea.me and load up both big and small files (especially big files) and you see how fast it uploads. I want it to upload as fast like https://filetea.me
If its possible to do that,it would be awesome.
While I remember. Do you know any other sites such as https://file.pizza that do the same thing as https://file.pizza then let me know

**Comment by kern** [comment]
We're using the [WebTorrent](https://github.com/feross/webtorrent) project for file transfers, so we're limited by the speed of its file transfers. I've updated our version of WebTorrent to the latest one, and I'm not seeing very slow speeds. Can you confirm @Ashtor? :)

**Comment by Ashtor** [comment]
Never mind that..
Maybe the reason for it is slow,is because of the filesize. Is it 
because of the filesize or is it because of the persons internet 
connection and speed or both? I might test it,but it will take a long 
time,since I barely use it. But when I can and got time,I check it.

Den 02.10.2016 02.12, skrev Alex Kern:

**Comment by kern** [comment]
It's probably limited by your internet connection or that of the uploader, not the file size. Closing since this isn't a FilePizza issue.
