### ISSUE TITLE
Remove Google Analytics

### ISSUE THREAD

**Issue by rugk** [kern/filepizza#57]
Do you really need to use a proprietary tracking service such as Google Analytics in FilePizza?

At least you should provide an option to disable it for self-hosted installations.

**Comment by kern** [comment]
Happy to accept a PR to disable it.

**Comment by FibreFoX** [comment]
This issue should be closed, as this is already added via https://github.com/kern/filepizza/pull/87

**Comment by rugk** [comment]
Okay, so fixed by https://github.com/kern/filepizza/pull/87
