### ISSUE TITLE
How top change path to socket.io correctly?

### ISSUE THREAD

**Issue by rugk** [kern/filepizza#58]
I'd like to change the socket.io path from `/socket.io` to  `/mySubDir/socket.io`. How can I do that properly?

**Comment by kern** [comment]
Let's keep the discussion in #59.

**Comment by rugk** [comment]
Well... this is a question and you have not answered it in any issue. (I thought you might answer this question and close the issue afterwards, so that the general issue can still be tracked in https://github.com/kern/filepizza/issues/59)
