### ISSUE TITLE
Installation in subdirectory difficult

### ISSUE THREAD

**Issue by rugk** [kern/filepizza#59]
As most paths are hardcoded and begin with `/` installing this project in a subdir is very difficult. https://github.com/kern/filepizza/issues/58 is part of this issue.

It would be very nice to have some configuration options to set a subdir path or to make it compatible with subdir installations out-of-the-box by using relative paths.

**Comment by kern** [comment]
Happy to accept a PR for this. I don't have a need for it, personally, but it seems reasonable.
