### ISSUE TITLE
Add support for directories

### ISSUE THREAD

**Issue by dessalines** [kern/filepizza#61]
I think this could be done using `<input type="file" webkitdirectory directory multiple/>`

EDIT: I've noticed that https://instant.io does have support for multiple files.

**Comment by dessalines** [comment]
Any updates?

**Comment by kern** [comment]
It's on my 2017 to-do list to rewrite this project with Redux and a better encryption scheme. Likely will support multiple files then. Til I have a spare moment, probably won't get around to this.

In the meantime you might be able to zip files. Maybe not the best solution, but it works! :)

**Comment by dessalines** [comment]
@kern Thanks!
