### ISSUE TITLE
Doesn't work with iOS 10 (even with Bowser)

### ISSUE THREAD

**Issue by chirale** [kern/filepizza#62]
I'm having trouble getting a filepizza instance (file.pizza) to work with iOS 10 as client on download.

I've tried with Firefox, Chrome and Bowser and all of them return "400: No WebRTC Support": https://www.openwebrtc.org/bowser/

Thank you for this incredible piece of software!

**Comment by bernhardc** [comment]
iOS 11 now added WebRTC support. http://caniuse.com/#feat=rtcpeerconnection
Still couldn't get it to work though.

**Comment by kern** [comment]
seems to work on latest iOS, please reopen if issue persists
