### ISSUE TITLE
Use shorter urls

### ISSUE THREAD

**Issue by stonewareslord** [kern/filepizza#65]
Would it be possible to replace the four toppings with a five letter code so it's easier to type? 

Example: replace `https://file.pizza/limburger-squash-chickentikka-pinenuts` with `https://file.pizza/uNU30`

Perhaps each topping list would have a corresponding 5 digit code and either could be typed in to redirect to the same file. Both could be shown at the time of uploading to give users a choice to use the topping url or shortcode url.

**Comment by onny** [comment]
I tried to overwrite the token string for this and adapted the routing url regex but it didn't work for me. All I get is 404 file not found :(

**Comment by mitchellpontague** [comment]
@onny is on the right track, but you will need to update the regex at `lib/middleware/bootstrap.js` aswell as the route params at `lib/routes.js`

**Comment by dessalines** [comment]
I'd rather have a QR code, scanning that is a lot easier than typing in.

**Comment by stonewareslord** [comment]
@dessalines A QR code would be nice, but my use case is sharing between two computers and manually typing in the URL (maybe even through a phone call).

**Comment by kern** [comment]
implemented in 1.1.0, now live on https://file.pizza :)
