### ISSUE TITLE
QR codes for tempalinks

### ISSUE THREAD

**Issue by alexs77** [kern/filepizza#69]
Would be great, if a QR code would be created on-the-fly, when a tempalink is created. Those long URLs are, well, long. And if one just wants to send a file from PC to smartphone or from one smartphone to another, it would be much easier, if a QR would be shown.

**Comment by Sanyy** [comment]
Yeah, could be placed on the site.

A "quick" (couple of clicks) workaround on chromium browsers:
https://chrome.google.com/webstore/detail/quick-qrcode/ijoeanckpfaegjkbdmbihinbdpgpcbba

-> you can save/send/read the image now

I think the link should be protected with a password and with a confirmation too to allow the download, it is not private at all now, till the tab is open **the file is available to anyone who saw this link.**

Till it is not available **i suggest to use gpg** /or aescrypt/ (if you choose _aescrypt_ you must share the code securely and it has to be installed on the other side as well) **to encrypt the files for the recipient**. Takes a couple of minutes on large files but this way only the recipient can use the file.
