### ISSUE TITLE
Problem preparing large files

### ISSUE THREAD

**Issue by Joohansson** [kern/filepizza#73]
Processing files over 500MB are not possible in Chrome as you say but not in my Firefox either. The pizza is rolling forever even with 600MB. MS Edge can handle larger files but it takes very long time. Is it possible to speed up? Would it be faster running own host compared to https://file.pizza? How to make it work with larger files than 10GB? I would need at least 100GB and working on Windows server 2012 (MS Edge not an option).

100MB: 7s
500MB: 17s
1GB: 42s
2GB: 1min
12GB: Didn't work. Page just reloaded after 4min

**Comment by Joohansson** [comment]
It worked in firefox after updating to latest version (56.0.1 64bit). 12GB in 1min but I can't get it to work with over 15GB it seems.

**Comment by arteniioleg** [comment]
I tried to send a 1.5Gb file from my phone but got endless Processing...

https://justbeamit.com creates a link without any processing.

**Comment by tshirtman** [comment]
Same issue here with a very large file, i hoped to use this system to move a 65G file over two computers on the same network, seems to load forever.
