### ISSUE TITLE
server down?

### ISSUE THREAD

**Issue by jligeza** [kern/filepizza#79]
Tried it last week, and today the server still doesn't respond. Is it down permanently?

**Comment by kern** [comment]
working to get it back up, thanks for the report @jligeza!

**Comment by jligeza** [comment]
Thank you for fix, file pizza is the best.

**Comment by Siecje** [comment]
Today I'm getting a 404 when I visit the given link.

**Comment by Siecje** [comment]
I am using a computer in Germany and it can't send or receive files from my computer in Canada.

It used to work. I don't know if it is a file.pizza bug.

The screen is just the normal 404 page for example https://file.pizza/dne
