### ISSUE TITLE
contact information for FilePizza

### ISSUE THREAD

**Issue by imthenachoman** [kern/filepizza#80]
I am looking to use FilePizza at my work (large corporation) but before it can be approved for use they need contact details for someone @ FilePizza. I need a name and an e-mail address. Is there anyway I can get that information?

**Comment by wucke13** [comment]
Have a look on the [owner](https://kern.io/) of the repo?

**Comment by dessalines** [comment]
These repos don't exist to fulfill your business requirements. Use it or don't.

**Comment by imthenachoman** [comment]
@wucke13 That is fantastic. Thank you so much!

**Comment by imthenachoman** [comment]
@dessalines I am not sure what you mean or what you're getting at. I'm just asking a question about contacting the owner. I'm not demanding to use it or making any absurd expectation of anyone.
