### ISSUE TITLE
please clarify encryption in the README

### ISSUE THREAD

**Issue by pts** [kern/filepizza#81]
Are files copied by file.pizza end-to-end encrypted in a way that only the sender and the receiver are able to decrypt the file, and other peers (possibly controlled by the attacker whose goal is steal file.pizza file contents) connecting to the same WebTorrent trackers can't?

How (by which ciphers and encryption primitives and when) is this encryption implemented?

I understand that WebRTC encrypts the data in transit, but this doesn't prevent the tracker from publishing IP addresses etc. through which the plaintext can be downloaded.

Please clarify this in the README.

**Comment by v6** [comment]
I have the same question. @bartdzkan, ahem.
