### ISSUE TITLE
Firefox runs out of memory while "processing"

### ISSUE THREAD

**Issue by afontenot** [kern/filepizza#83]
I haven't looked at the source, but I suppose it's hashing the file so it can be shared as a webtorrent? It seems like *at least* the whole file is going into memory. I have over 8 GB of free RAM right now, and my computer hung after file.pizza ate it all while processing a 6 GB file. 

If there's anything I can do to help debug this, let me know. 

    Firefox 61.0.1

    Linux host 4.17.9-1-ARCH #1 SMP PREEMPT Sun Jul 22 20:23:36 UTC 2018 x86_64 GNU/Linux

**Comment by afontenot** [comment]
Additional info: same problem on the latest Chromium. 

Also, reep.io does not have this problem on the uploading side (in Firefox). On download, reep.io goes to memory in Firefox and the tab crashes when it tries to trigger the download. In Chromium, the file gets cached in `~/.config/chromium`.

**Comment by Flauschbaellchen** [comment]
Same issues arise on our installations.
Is it possible to hash the file without loading it into memory?

**Comment by dessalines** [comment]
Could yall test to see if https://instant.io/ has the same problem with large files? Its the only one I've been able to get working consistently.
