### ISSUE TITLE
Input for ingredients to get the download

### ISSUE THREAD

**Issue by Madis0** [kern/filepizza#85]
Some users are lazy or just not enough familiar with computers to type the full URL when told.

What if you could add a text field to the homepage where a user can just type the four words (autocomplete would help, too) and they will be taken to the result download page?

**Comment by kern** [comment]
Happy to accept PRs that implement this, although I think the QR code and new shortcodes do a good job of this.

**Comment by Erquint** [comment]
This sounds fun!
