### ISSUE TITLE
Website doesn't redirect https version. 

### ISSUE THREAD

**Issue by dean992008** [kern/filepizza#95]
Hi!
Actual result:
Website http://file.pizza/ possible open with http. In this case Google Chrome don't enable WebRTC connection. 
Expected result:
http://file.pizza/ redirect to https://file.pizza/. 
![90c09810c7](https://user-images.githubusercontent.com/11517379/58180546-f94b5f00-7cb2-11e9-9a93-3cdaab0b8663.jpg)

**Comment by kern** [comment]
fixed — thanks for the heads up!
