### ISSUE TITLE
Footer with Bitcoin wallet and info jumps around on mobile

### ISSUE THREAD

**Issue by alexs77** [kern/filepizza#98]
On my Huawei P30 with the Huawei Browser, the footer with the Bitcoin wallet and other information on the bottom of the screen constantly jumps around.

Please have a look at this video: https://photos.app.goo.gl/5mnJ8gF71JSb9Mfr6

The video is also attached here, as a ZIP: [SVID_20190603_094832_1.mp4.zip](https://github.com/kern/filepizza/files/3246454/SVID_20190603_094832_1.mp4.zip)

**Comment by kern** [comment]
should be fixed in 1.1.0 (now live on `file.pizza`), please reopen if issue persists
